### ISSUE TITLE
Add schema support for strings as sample indices in `output_type_id`

### ISSUE THREAD

**Issue by elray1** [hubverse-org/schemas#61]
Per discussion related to #48, in a first pass we will only support integer sample indices for `output_type_id`, but we would eventually like to support strings as well. To do this, we will need to add two properties to the `output_type_id` field in a hub's `tasks.json` config file:

- “type”: the data type of the sample index. `"string"` or `"integer"`
- “max_length”: if `"type"` is `"string"`, the maximum number of characters in a sample index

`"max_length"` should be required if `"type"` is `"string"`, but not otherwise.

**Comment by nickreich** [comment]
relating this to issue #70

**Comment by annakrystalli** [comment]
This is superceeded by #70 correct? My understanding is that there is no `output_type_id` property for samples anymore and all this is specified in `output_type_id_params`, correct?
