### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mzorn-58** [hubverse-org/schemas#62]
[specific documentation about the schema files](https://hubdocs.readthedocs.io/en/latest/format/hub-metadata.html)

**Comment by mzorn-58** [comment]
[Here ](https://github.com/Infectious-Disease-Modeling-Hubs/schemas#readme))is the readme with the broken link.

**Comment by micokoch** [comment]
From what I can tell, this was already resolved, as the link is no longer broken.
