### ISSUE TITLE
admin-schema.json: split repository_url property into org name and repository name

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/schemas#67]
As we onboard hubs to the cloud, splitting the `admin-schema.json` `repository_url` property into its atomic components of GitHub organization and repository name would be a helpful change. Or, alternately, combine these items and `repository_host` into a single `repository` group.

Reason: cloud-enabled hubs need the GitHub org name and repo name as separate strings for setting up AWS permissions. 

Because we know that all hubs are currently hosted on GitHub, it's not worth introducing a breaking schema change right now (we can parse out org and repo name as needed). But logging this suggestion to consider the next time we do a breaking upgrade.

**Comment by bsweger** [comment]
@annakrystalli great, thanks for remembering this!

Having the repo and org as separate fields will be great. I can't think of specific checks (other than data type)...I'd be worried that more detailed checks would fail if someone was trying to set up a hub using a private repo.

**Comment by annakrystalli** [comment]
I've gone for the `repository` object approach in the end, feel it's cleaner.
