### ISSUE TITLE
Allow additional properties?

### ISSUE THREAD

**Issue by LucieContamin** [hubverse-org/schemas#74]
To solve a file size issue in GitHub, US SMH allows team to partition their `parquet` files. However, we are forcing which partition they should follow. I think it will be interesting for us to store that information maybe in the `tasks.json` file so that we can check the partition per round. 
Currently, I am adding the information in the `json` and ignore the error in the validation `validate_config()`. However, I was wondering if it makes sense to allow to add some additional properties that are ignored in the validation and other functions?

**Comment by annakrystalli** [comment]
This was discussed at a recent hub developers meeting and the decision was to support some additional properties. Because this relaxation can allow errors in the location of objects to not be picked up, we limit the lifting of the restriction to only the round item level for now.
