### ISSUE TITLE
remove epidemic week formatting requirements for CDF category values

### ISSUE THREAD

**Issue by elray1** [hubverse-org/schemas#80]
I just noticed that the schema requires that the CDF values are either numeric or are strings in the format of an epidemic week, e.g. "EW202204".  I don't think there's a reason to impose this formatting requirement, though -- one could imagine collecting CDF predictions for an ordinal categorical variable other than epidemic weeks with strings naming the categories that don't match that format.

For example, looking here: https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/2e79b13d309168824bcca7ef716ebeb9aa3cda44/v3.0.0/tasks-schema.json#L948-L953

**Comment by annakrystalli** [comment]
Quick question, we want min and max removed also right? https://github.com/hubverse-org/schemas/blob/2e79b13d309168824bcca7ef716ebeb9aa3cda44/v3.0.0/tasks-schema.json#L951-L952

**Comment by elray1** [comment]
yeah, i agree that it makes sense to remove those too
